name: rent_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  permission_handler: ^5.0.1+1
  provider:
  google_sign_in:
  cloud_firestore:
  flare_flutter:
  firebase_auth:
  christian_picker_image: ^0.1.7
  cached_network_image: ^2.2.0+1
  flutter_map:
  user_location:
  geolocator: ^5.3.2+2
  flutter_map_marker_popup: ^0.1.4
  flutter_staggered_grid_view: "^0.2.7"
  firebase_storage: ^3.1.6
  persistent_bottom_nav_bar: ^2.0.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  shimmer:
  latlong:
  vector_math: ^2.0.0
  proj4dart: ^1.0.4
  geo_firestore: ^0.0.1
  location: ^3.1.0
  google_fonts:
  path_provider:
  animations: ^1.1.2
  loading: ^1.0.2
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/flare_animations/house.flr
    - assets/loading/loader.gif
    - assets/loading/map_loader.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Bold.ttf
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Light.ttf
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
